# Generated by Django 5.1.5 on 2025-02-05 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nodes_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=45, unique=True)),
                ('GPS_Koordinat', models.CharField(max_length=45)),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='realtimes_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('Pressure', models.FloatField()),
                ('Status_cam', models.BooleanField(default=True)),
                ('Status_gauge', models.BooleanField(default=True)),
                ('File_image', models.CharField(max_length=100)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='vision_app.nodes_model')),
            ],
        ),
    ]
