# Generated by Django 5.1.5 on 2025-02-17 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nodes_model',
            fields=[
                ('node_id', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('GPS_Koordinat', models.CharField(max_length=45)),
                ('Merk', models.CharField(blank=True, max_length=45, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('zona_instalasi', models.CharField(blank=True, max_length=10, null=True)),
                ('isolasi', models.CharField(blank=True, max_length=10, null=True)),
                ('min_scale', models.FloatField(blank=True, null=True)),
                ('max_scale', models.FloatField(blank=True, null=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('IP', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ultg_model',
            fields=[
                ('ULTG', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ULTG_Koordinat', models.CharField(max_length=45)),
                ('Alamat', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='upt_model',
            fields=[
                ('UPT', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('UPT_Koordinat', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='image_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='vision/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_data', to='vision_app.nodes_model')),
            ],
        ),
        migrations.CreateModel(
            name='realtimes_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('Pressure', models.FloatField()),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('Status_cam', models.CharField(default='on', max_length=45)),
                ('Status_gauge', models.CharField(default='aman', max_length=45)),
                ('File_image', models.ImageField(blank=True, null=True, upload_to='vision/')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtimes_data', to='vision_app.nodes_model')),
            ],
        ),
        migrations.CreateModel(
            name='unit_model',
            fields=[
                ('GIS', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('GPS_Koordinat', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ULTG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultg_id', to='vision_app.ultg_model')),
                ('UPT', models.ForeignKey(default='UPT_Pulogadung', on_delete=django.db.models.deletion.CASCADE, related_name='upt_ids', to='vision_app.upt_model')),
            ],
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_tes', to='vision_app.unit_model'),
        ),
        migrations.AddField(
            model_name='ultg_model',
            name='UPT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upt_id', to='vision_app.upt_model'),
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.CharField(blank=True, max_length=100, null=True)),
                ('no_hp', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('unit', models.ManyToManyField(to='vision_app.unit_model')),
            ],
        ),
    ]
