# Generated by Django 5.1.5 on 2025-02-06 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes_model',
            name='Merk',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='isolasi',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='type',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='zona_instalasi',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='realtimes_model',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtimes_data', to='vision_app.nodes_model'),
        ),
    ]
