# Generated by Django 5.1.5 on 2025-02-17 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_model',
            name='UPT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upt_ids', to='vision_app.upt_model'),
        ),
    ]
