# Generated by Django 5.1.5 on 2025-02-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0002_nodes_model_merk_nodes_model_isolasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimes_model',
            name='Status_cam',
            field=models.CharField(default='on', max_length=45),
        ),
        migrations.AlterField(
            model_name='realtimes_model',
            name='Status_gauge',
            field=models.CharField(default='aman', max_length=45),
        ),
    ]
