# Generated by Django 5.1.5 on 2025-02-17 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0003_remove_unit_model_upt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unit_model',
            new_name='GI_model',
        ),
        migrations.RemoveField(
            model_name='nodes_model',
            name='unit',
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='GIS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GI_tes', to='vision_app.gi_model'),
        ),
    ]
