# Generated by Django 5.1.5 on 2025-02-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0004_rename_unit_model_gi_model_remove_nodes_model_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ultg_model',
            old_name='UPT',
            new_name='UPT_1',
        ),
    ]
