# Generated by Django 5.1.5 on 2025-01-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='realtime_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_ID', models.CharField(max_length=50, unique=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Pressure', models.FloatField()),
                ('Status_Cam', models.BooleanField(default=True)),
                ('Status_Normal', models.BooleanField(default=True)),
                ('File_image', models.CharField(max_length=500)),
            ],
        ),
    ]
