# Generated by Django 5.1.5 on 2025-01-30 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_realtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtime_data',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
