# Generated by Django 5.1.5 on 2025-01-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_realtime', '0002_alter_realtime_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtime_data',
            name='nilai',
            field=models.IntegerField(auto_created=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtime_data',
            name='Node_ID',
            field=models.CharField(max_length=50),
        ),
    ]
