# Generated by Django 5.1.5 on 2025-01-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_realtime', '0003_realtime_data_nilai_alter_realtime_data_node_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtime_data',
            name='nilai',
        ),
    ]
